server:
  port: 8080

logging:
  level:
    root: INFO
    no:
      lagalt:
        lagaltbackend: DEBUG
    org:
      springframework:
        boot:
          autoconfigure: INFO
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/lagalt_db
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    tomcat:
#      max-wait: 20000
#      test-on-borrow: true
#      test-while-idle: true
#      validation-query: SELECT 1
#      validation-query-timeout: 1000
#      validation-interval: 1000
#